### ISSUE TITLE
Browser hangs indefinitely for a number of notification events

### ISSUE THREAD

**Issue by vasiliyfomichev** [vasiliyfomichev/Slack-for-Sitecore#3]
The browser hangs indefinitely when the following events have been set to post:
- [x] Campaign
- [x] Event
- [x] List Creation
- [x] List Deletion
- [x] Test Start
- [x] Test Stop
- [x] Page Test Start

**Comment by colema18** [comment]
I accidentally named the branch that fixes this as "bugfix/issue-1" instead of "bugfix/issue-3". But in anycase I have merged the branch fix into master. I am going to close and after you guys test if there is still an issue we will just create a new issue since I botched the branch name already.
